### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by staticdreams** [ricardopereira/QuickActions#2]
Hello Ricardo,

Thanks for this module . I was looking forward an easier solution of implementing Quick Actions with my app. However, I ran into some installation issues. Module is installed correctly and recognised with "import" statement at the beginning of my AppDelegate, but then there are some problems:

`Use of undeclared type 'ShortcutType'`
`Cannot specialize non-generic type 'module<QuickActions>'`

Truth be told I'm just following the steps you outlined in the readme file. At this point I'm just guessing which part goes where in my app. Could you please provide and example application for everyone to use as kickstart ?

**Comment by ricardopereira** [comment]
Can you try with v1.2?
I fixed it with 813eeda.

**Comment by ricardopereira** [comment]
Even so, I will create an Example project.
Thank you for pointing this out.

**Comment by staticdreams** [comment]
Actually it wasn't working with Cocoapods installation. So I imported the file directly and it worked.

**Comment by ricardopereira** [comment]
What was wrong with CocoaPods?
Can you share the log?

**Comment by staticdreams** [comment]
Nothing wrong. I mean it installed correctly and I was able to use `import QuickActions` statement without any warnings. But it just wouldn't recognise `ShortcutType` or my instantiating of QuickActions ..
After that I uninstalled cocopod and dragged the file directly into my project and it worked fine

**Comment by ricardopereira** [comment]
The problem is fixed now. I was missing a couple of access levels: `public`.
You can go back to CocoaPods. I tested it.

**Comment by staticdreams** [comment]
ok, thank you! I also experience a few crashes. notably when not specifying a `subtitle` for quick action, although it is marked as optional. I had to specify it anyway to avoid crashes

**Comment by ricardopereira** [comment]
Please open an issue for that crash.
Thank you.
