### ISSUE TITLE
Somehow not working to me. Anyone works?

### ISSUE THREAD

**Issue by Tim77277** [ricardopereira/QuickActions#7]
I ran into one problem and couldn't figure it out what happened. I followed the instructions in the README and also checked the example code, however in performActionForShortcutItem function

```swift
func application(application: UIApplication, performActionForShortcutItem shortcutItem:     UIApplicationShortcutItem, completionHandler: Bool -> Void) {
        guard let quickActions = quickActions else { return completionHandler(false) }
        guard let rootViewController = window?.rootViewController else { return completionHandler(false) }
        completionHandler(quickActions.handle(rootViewController, shortcutItem: shortcutItem))
}
```

This line always return false

```swift
quickActions.handle(rootViewController, shortcutItem: shortcutItem)
```
I don't know if it is because I set something wrong or it is because of the library.

**Comment by ricardopereira** [comment]
@Tim77277 You're using the latest version? Did you look the example? https://github.com/ricardopereira/QuickActions/tree/master/Example

**Comment by Tim77277** [comment]
**UPDATE:**
I just solved the problem. It wasn't library's problem. The reason it didn't work before was because I used a UISplitViewController in my project. So when the function inside completionHandler got called

```swift
quickActions.handle(rootViewController, shortcutItem: shortcutItem)
```

It always returned false simply because my rootViewController was not the controller that I want to handle the QuickActionSupport protocol.

Hopefully it would help some people who encounter the same problem as me.

**Comment by Tim77277** [comment]
**UPDATE:** 
I just solved the problem. It wasn't library's problem. The reason it didn't work before was because I use a UISplitViewController in my project. So when the function inside completionHandler got called

```swift
quickActions.handle(rootViewController, shortcutItem: shortcutItem)
```

It always returned false simply because my rootViewController is not the controller that I want to handle the QuickActionSupport protocol.

Hopefully it would help some people who encounter the same problem as me.

**Comment by ricardopereira** [comment]
Ok, thanks for sharing!
